### ISSUE TITLE
Webpack 4 Support?

### ISSUE THREAD

**Issue by brycehill** [unindented/stats-webpack-plugin#31]
Hi. Are there plans to make this work with webpack 4? I am currently getting this deprecation warning: 

```
(node:14247) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

Here is the full trace:

```
> node --trace-deprecation webpack --config client/config/webpack/webpack.config.js

(node:14523) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at StatsPlugin.apply (/Users/brycehill/workspace/clearvoice/node_modules/stats-webpack-plugin/index.js:22:12)
    at webpack (/Users/brycehill/workspace/clearvoice/node_modules/webpack/lib/webpack.js:37:12)
    at options.map.options (/Users/brycehill/workspace/clearvoice/node_modules/webpack/lib/webpack.js:28:55)
    at Array.map (<anonymous>)
    at webpack (/Users/brycehill/workspace/clearvoice/node_modules/webpack/lib/webpack.js:28:40)
    at processOptions (/Users/brycehill/workspace/clearvoice/node_modules/webpack-cli/bin/webpack.js:436:16)
    at yargs.parse (/Users/brycehill/workspace/clearvoice/node_modules/webpack-cli/bin/webpack.js:510:3)
    at Object.parse (/Users/brycehill/workspace/clearvoice/node_modules/webpack-cli/node_modules/yargs/yargs.js:543:18)
    at /Users/brycehill/workspace/clearvoice/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/Users/brycehill/workspace/clearvoice/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/brycehill/workspace/clearvoice/node_modules/webpack/bin/webpack.js:80:2)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by rpellerin** [comment]
Would love to see this fixed as well :)

**Comment by ChibiBlasphem** [comment]
@unindented Hello, could you please check the PR on this matter?

**Comment by unindented** [comment]
Sorry, didn't see this until now. Published version `0.7.0` with Webpack v4 support.

**Comment by eranimo** [comment]
I'm using webpack 4.17 and nothing is being outputted...

**Comment by unindented** [comment]
@eranimo I'm not using the plugin at the moment, so if you can fix whatever is wrong in a PR, I'll merge it. Thank you!
